package io.ctl.globalhack.model.service.constraint;

/**
 * Created by khomco on 10/22/16.
 */
public enum OccupancyConstraint {
    ACCEPTS_FAMILY, ACCEPTS_WOMEN, ACCEPTS_MEN,
    ACCEPTS_YOUTH, ACCEPT_SEX_OFFENDER, REQUIRES_REFERRAL,
    REQUIRES_HIV, ACCEPTS_HIV, ACCEPTS_PREGNANT, REQUIRES_SSN, ACCEPT_MEN_AND_WOMEN, REQUIRES_YOUTH, REQUIRES_PREGNANCY_OR_FAMILY;
}
